apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  annotations:
    cert-manager.io/issue-temporary-certificate: "true"
    kubernetes.io/ingress.regional-static-ip-name: vault-dns
spec:
  rules:
  - host: mypassvault.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vault-clsuter-svc
            port:
              number: 9000